name: PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  static_code_check:
    name: Run static code checkers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
      - name: Run spotless
        run: ./gradlew spotlessCheck

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Run test
        run: ./gradlew test

  build:
    name: Build jar
    runs-on: ubuntu-latest
    needs:
      - static_code_check
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build jar
        run: ./gradlew assemble
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: libcsv.jar
          path: 'lib/build/libs/libcsv-*.jar'
          if-no-files-found: error
